StaffingSystem/StaffingSystem/urls.py
#coding:utf-8
"""StaffingSystem URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from mainSystem import urls as mainSystem_urls
from mainSystem import views as mainSystme_views
from django.views.static import serve # 处理媒体文件的API
from django.conf import settings # 把django 的配置文件导入进来

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),  # ORM数据库
    url(r'^$',mainSystme_views.index,name='index'), #系统首页和主项目的首页设置成一样的
    # StaffingSystem和mainSystem都配置了login，
    # 这样127.0.0.1:8003/login和127.0.0.1:8003/mainSystem/login都能调取views的login函数了
    url(r'^login/$',mainSystme_views.login,name='login'),
    url(r'^logout/$',mainSystme_views.logout,name='logout'),
    url(r'^reg/$',mainSystme_views.reg,name='reg'),
    url(r'^mainSystem/',include(mainSystem_urls,namespace='mainSystem')),
    url(r'^checkname/$', mainSystme_views.checkname,name='checkname'),
    #写一个媒体文件的url 并且用serve函数处理 指定媒体文件的路径
    url(r'^upload/(.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
]

StaffingSystem/mainSystem/urls.py
#coding:utf-8

from django.conf.urls import url
import views
from django.views.static import serve # 处理媒体文件的API
from django.conf import settings # 把django 的配置文件导入进来

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^manage/$',views.manage,name='manage'),
    url(r'^advancedSearch/$',views.advancedSearch,name='advancedSearch'),
    url(r'^add_dpt/$',views.add_dpt,name='add_dpt'),
    url(r'^add_position/$',views.add_position,name='add_position'),
    url(r'^config/$',views.config,name='config'),#系统配置
    url(r'^empl_add/$',views.empl_add,name='empl_add'),
    url(r'^empl_edit/$', views.empl_edit,name='empl_edit'),
    url(r'^empl_del/$', views.empl_del,name='empl_del'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^reg/$',views.reg,name='reg'),
    # 写一个媒体文件的url 并且用serve函数处理 指定媒体文件的路径
    url(r'^upload/(.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^checkname/$', views.checkname,name='checkname'),
]

StaffingSystem/mainSystem/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User #MySQL扩展数据库用户表，一对一字段

# Create your models here.
class Employee(models.Model):
    name = models.CharField(verbose_name='姓名',max_length=20)
    age = models.IntegerField(verbose_name='年龄')
    telphone = models.CharField(verbose_name='手机',max_length=11)
    email = models.EmailField(verbose_name='邮箱',null=True,blank=True)
    add_date = models.DateTimeField(verbose_name='添加时间',auto_now_add=True)
    dpt = models.ForeignKey('Department')
    ptn = models.ForeignKey('Position')
    # 如果用ImageField字段类型 你需要安装Pillow模块  pip install Pillow
    # upload_to ： django-admin 上传路径
    avatar = models.ImageField(verbose_name='头像',upload_to='avatar',default='avatar/default.jpg')
    #upload_to = 'avatar', default = 'avatar/default.jpg'是给admin的ORM后台用的
    group = models.ManyToManyField('Group',verbose_name='参加社团')# 跟group公司社团表建立多对多关系

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = '员工信息'

class Department(models.Model):
    name = models.CharField(verbose_name='部门名称',max_length=30,null=True,blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = '部门信息'


class Position(models.Model):
    name = models.CharField(verbose_name='职位',max_length=30)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = '职位信息' #ORM表名称显示成中文

class UserProfile(models.Model):
    telphone = models.CharField(verbose_name='手机',max_length=11)
    nick = models.CharField(verbose_name='昵称',max_length=30)
    user = models.OneToOneField(User)   #一对一关联扩展Django用户表

    class Meta:
        verbose_name = verbose_name_plural = '用户信息'


    def __unicode__(self):
        return self.nick #返回中文昵称

class Group(models.Model):
    name = models.CharField(verbose_name='社团名称',max_length=30)
    # group_ledder =    #社长

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = verbose_name_plural = '社团'

StaffingSystem/mainSystem/views.py
#coding:utf-8
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import models
from django.db.models import Q #用于搜索功能
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger  #用于分页处理、异常处理
from django.contrib.auth.decorators import login_required   #引入装饰器，用于登录之前的验证
from django.contrib import auth # 用于 登录 退出 验证
from django.contrib.auth.hashers import make_password #注册时密码用于加密
from django.contrib.auth.models import User
import os  #在这里用于文件存取
import uuid # 生成唯一标识符上传图片是用的
# Create your views here.

@login_required #引入装饰器，用于登录之前的验证
#########################################################################
def index(request):
    wd = request.GET.get('wd',None)     #用于搜索和排序的连调
    order = request.GET.get('order',None)   #用于排序字段
    rule = request.GET.get('rule',None)     #用于排序规则
    pn = request.GET.get('pn',1)    #刚进网页时，pn没有值默认指定为pn=1

    # pn 传过来时是Unicode类型，要转为int类型
    try:
        pn = int(pn)
    except Exception as e:  #第一次书写时except后面加了个:号导致错误，以后注意
        pn = 1
    #----------搜索功能-------------
    if wd is not None:
        # 一个Q就是一个条件 然后用并集操作符连接
        condition = Q(name__icontains=wd) | Q(age__icontains=wd) | Q(telphone__icontains=wd) | Q(email__icontains=wd)\
         | Q(dpt__name__icontains=wd) | Q(ptn__name__icontains=wd)
        empls = models.Employee.objects.filter(condition)   #根据条件获取员工对象
        # 耿健琪写的
        # a = models.Student.objects.filter(name__icontains=wd)
        # b = models.Student.objects.filter(score__icontains=wd)
        # stus = a | b
    else:
        empls = models.Employee.objects.all()  # 获取全部员工对象，放在这里实现搜索后排序,分页

    #-----------------排序功能-------------------
    if order is not None:
        if rule == 'u': #升序
            empls = empls.order_by(order)
        else:   #降序
            empls = empls.order_by(order).reverse()

    #-----------------分页-----------------------
    setPageNums = 3  # 用于设置每页显示的条数
    per_page = request.COOKIES.get('per_page',setPageNums)# 从客户端浏览器中读取每页显示记录条数的cookie值
    setPageNums = per_page    #用于设置每页显示的条数,利用cookie设置每页显示条数
    try:
        paginator = Paginator(empls,setPageNums) #返回一个分页对象，p1:Queryset p2:每页记录条数
        empls = paginator.page(pn) # 获取某一页的记录
    except (InvalidPage,EmptyPage,PageNotAnInteger) as e:
        pn = 1 #出现异常就跳到第一页
        paginator = Paginator(empls, setPageNums)
        empls = paginator.page(pn)  # 获取某一页的记录
        print e

    sumPages = empls.paginator.num_pages    #获取总页数

    #分页数字生成
    setPages = 5    #设置底部要显示的页码数，想要显示的数字个数
    if sumPages < setPages: # 最大页数小于你想要显示的数字个数
        start =1
        end = sumPages +1
    else:   # 最大页数大于等于你想要显示的数字个数
        if pn <= 2:     # 页数左边界
            start = 1
            end = setPages +1
        elif pn >= sumPages - 2:    #页数右边界
            start = sumPages - (setPages - 1)
            end = sumPages + 1  #加1是因为range左闭右开
        else:
            start = pn - int(setPages/2)
            end = pn + int(setPages/2) + 1



    page_nums = range(start,end)
    context = {
        'index':'active',
        'empls':empls,
        'page_nums':page_nums,
    }
    return render(request,'mainSystem/index.html',context)

######################################################################
#用于左侧边栏点击效果、页面跳转
def manage(request):
    context = {
        'manage':'active'
    }
    return render(request,'mainSystem/manage.html',context)

#######################################################################
#左侧边栏系统配置页面
def config(request):
    per_page = request.GET.get('per_page', None)  # 获取用户提交过来的每页显示记录条数
    context = {
        'config':'active',

    }
    if per_page is None:# 默认访问配置页则显示配置模板
        return render(request, 'mainSystem/config.html', context)
    else:# 提交的每页显示记录条数
        rep = HttpResponseRedirect('/mainSystem/config/')
        rep.set_cookie('per_page', per_page, max_age=3600 * 24 * 365)  # 设置一个长期有效cookie 每页记录条数
        return rep  # 做一个Http响应

#######################################################################
#左侧边栏高级查询页面
def advancedSearch(request):
    context = {
        'advancedSearch':'active'
    }
    return render(request, 'mainSystem/advancedSearch.html', context)

######################################################################
#增加部门
def add_dpt(request):
    # models.Department(name='销售部').save()
    # models.Department(name='行政部').save()
    # models.Department(name='技术部').save()
    # models.Department(name='后勤部').save()
    # models.Department(name='财务部').save()
    # models.Department(name='法务部').save()
    # models.Department(name='设计部').save()
    return HttpResponse('OK')


######################################################################
#增加职位
def add_position(request):
    # models.Position(name='总经理').save()
    # models.Position(name='副总经理').save()
    # models.Position(name='销售总监').save()
    # models.Position(name='财务总监').save()
    # models.Position(name='技术总监').save()
    # models.Position(name='经理').save()
    # models.Position(name='职员').save()
    # models.Position(name='技术员').save()
    # models.Position(name='总工程师').save()
    return HttpResponse('OK')

######################################################################
# 上传文件函数，代码复用
def upload(request,file): # file就是上传的文件
    if file.size / 1024 / 1024 < 2: #判断文件上传大小
        if file.content_type == 'image/jpeg' or file.content_type == 'image/gif': #判断文件类型
            # 把文件存到服务器上了
            # 按照文件名的.进行分割 然后取最后一项后缀名
            #uuid.uuid4()前面要导入import uuid # 生成唯一标识符
            new_name = str(uuid.uuid4()) + '.' + file.name.split('.')[-1]  # lelkr.jpg  kljer.gif

            fname = 'upload/avatar/' + new_name

            dirname = os.path.dirname(fname)  #获取路径名称

            if not os.path.exists(dirname): #如果不存在这个路径就创建一个

                os.makedirs(dirname)    # 创建多级目录
            ##----文件写入----
            with open(fname,'wb') as f: #二进制，写入打开方式
                if file.multiple_chunks():  # 多块文件
                    for chunk in file.chunks(): # 遍历文件的所有块
                        f.write(chunk)
                else: #单块文件
                    f.write(file.read())
            return True,new_name    # 上传成功返回True 和 文件的新名字
        else:
            return False,'文件类型只能是jpg或者gif'#返回False 和错误描述信息
    else:
        return False,'文件大小不能超过2M'   #返回False 和错误描述信息


######################################################################
#增加员工
def empl_add(request):
    if request.method == 'POST':
        name = request.POST.get('name',None)
        age = request.POST.get('age',None)
        telphone = request.POST.get('telphone',None)
        email = request.POST.get('email',None)
        dpt_id = request.POST.get('dpt_id',None)    # 部门id
        ptn_id = request.POST.get('ptn_id',None)    #职位id
        # 用过FILES字典获取单个上传文件 avatar是通过模板里intput标签的name属性决定的
        avatar = request.FILES.get('avatar',None)   # 获取到一个文件对象
        # print avatar.content_type # 文件上传类型
        # print avatar.size # 文件大小 单位是字节
        # print avatar.name # 文件名
        # print avatar.multiple_chunks() # 如果文件大于2.5M的时候返回True 反之返回False
        # return HttpResponse('ok')

        if avatar is not None:  # 如果文件不是None则获取文件对象成功
            res = upload(request,avatar)    #调用自己写的上传函数
            if res[0] is False: # 如果上传失败则返回错误描述
                return render(request,'mainSystem/empl_add.html',{'error':res[1]})
            else:   #上传成功
                new_name = res[1] # 获取返回的文件名字

        stu_info = {
            'name':name,
            'age':age,
            'telphone':telphone,
            'email':email,
            'dpt_id':dpt_id,
            'ptn_id':ptn_id,
            'avatar':'avatar/' + new_name # 头像的路径
        }
        models.Employee.objects.create(**stu_info)  #增加员工信息
        return HttpResponseRedirect('/')    #返回主页

    else:#get请求，没有传值的时候修改样式
        departments = models.Department.objects.all()   #获取部门对象
        positions = models.Position.objects.all()  # 获取职位对象
        context = {
            'manage':'active',#选中样式
            'departments':departments,
            'positions':positions,
        }
        return render(request,'mainSystem/empl_add.html',context)


######################################################################
#修改员工信息
def empl_edit(request):
    eid = request.GET.get('eid',None)   #获取要修改的员工的id
    if request.method == 'POST':
        name = request.POST.get('name', None)
        age = request.POST.get('age', None)
        telphone = request.POST.get('telphone', None)
        email = request.POST.get('email', None)
        dpt_id = request.POST.get('dpt_id', None)  # 部门id
        ptn_id = request.POST.get('ptn_id', None)  # 职位id
        avatar = request.FILES.get('avatar', None)  # 获取到一个文件对象
        # print avatar.content_type # 文件上传类型
        # print avatar.size # 文件大小 单位是字节
        # print avatar.name # 文件名
        # print avatar.multiple_chunks() # 如果文件大于2.5M的时候返回True 反之返回False
        # return HttpResponse('ok')

        if avatar is not None:  # 如果文件不是None则获取文件对象成功
            res = upload(request, avatar)  # 调用自己写的上传函数
            if res[0] is False:  # 如果上传失败则返回错误描述
                return render(request, 'mainSystem/empl_add.html', {'error': res[1]})
            else:  # 上传成功
                new_name = res[1]  # 获取返回的文件名字
        stu_info = {
            'name': name,
            'age': age,
            'telphone': telphone,
            'email': email,
            'dpt_id': dpt_id,
            'ptn_id': ptn_id,
            'avatar':'avatar/' + new_name #头像路径
        }
        models.Employee.objects.filter(id=eid).update(**stu_info)  # 修改员工信息
        return HttpResponseRedirect('/')  # 返回主页
    else:#没有传值的时候调用
        empl = models.Employee.objects.get(id=eid)  #获取要修改的员工对象
        departments = models.Department.objects.all()   #获取部门对象
        positions = models.Position.objects.all()   #获取职位对象
        return render(request,'mainSystem/empl_add.html',{'empl':empl,'departments':departments,'positions':positions})

######################################################################
#删除员工

StaffingSystem/templates/mainSystem/base.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN" data-livestyle-extension="available"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'mainSystem/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'mainSystem/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'mainSystem/css/dashboard.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'mainSystem/js/ie-emulation-modes-warning.js'%}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">员工管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
{#            <li><a href="#">注册</a></li>#}<!--登录后无需注册-->
            <li><a href="#">{{ request.user.userprofile.nick }}</a></li>    <!--登录成功后显示，用户昵称，里面为一对一扩展的联调方式-->
            <li><a href="{% url 'mainSystem:logout' %}">退出</a></li>
          </ul>
          <form class="navbar-form navbar-right" action="{% url 'index' %}">    <!--搜索框容易忘掉，设置后在所有地方都可搜索-->
            <input type="text" name="wd" class="form-control" placeholder="Search..."> <!--name="wd"向views后台提交数据-->
              <input type="submit" class="btn btn-primary"> <!--#提交按钮-->
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
       {% include 'mainSystem/menu.html' %} <!--获取到左侧按钮模板-->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block main %}
            {% endblock %}

        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'mainSystem/js/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'mainSystem/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'mainSystem/js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'mainSystem/js/ie10-viewport-bug-workaround.js' %}"></script>


</body></html>

StaffingSystem/templates/mainSystem/config.html
{% extends 'mainSystem/base.html' %}

{% block main %}
    <form class="form-horizontal" action="" method="get">
        <div class="form-group">
            <label class="control-label col-sm-2">每页显示条数</label>
            <div class=" col-sm-6">
                <input class="form-control" type="text" name="per_page" value="{{ request.COOKIES.per_page }}">
            </div>
            <input type="submit" value="保存">

        </div>
    </form>
{% endblock %}

StaffingSystem/templates/mainSystem/index.html
{% extends 'mainSystem/base.html' %}
{% load static %}
{% block css  %}
    <link rel="stylesheet" href="">
{% endblock %}
{% block main %}
    <table class="table table-bordered table-hover">
        <tr id="myheadtr">
            <th>头像</th>
            <th>姓名
                <a href="?order=name&rule=u&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></a>
                <a href="?order=name&rule=d&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></a>
            </th>
            <th>年龄
                <a href="?order=age&rule=u&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></a>
                <a href="?order=age&rule=d&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></a>
            </th>
            <th>电话
                <a href="?order=telphone&rule=u&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></a>
                <a href="?order=telphone&rule=d&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></a>
            </th>
            <th>邮箱
                <a href="?order=email&rule=u&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></a>
                <a href="?order=email&rule=d&wd={{ request.GET.wd }}"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></a>
            </th>
            <th>部门</th>
            <th>职位</th>
            <th>职级</th>
            <th>社团</th>
            <th>管理</th>
        </tr>
         {% for empl in empls %}
        <tr>
            <td><img src="{{ empl.avatar.url }}" width="50" height="50"></td>
            <td>{{ empl.name }}</td>
            <td>{{ empl.age }}</td>
            <td>{{ empl.telphone }}</td>
            <td>{{ empl.email }}</td>
            <td>{{ empl.dpt.name }}</td>
            <td>{{ empl.ptn.name }}</td>
            <td>
                {% if empl.ptn.id <= 4 %}
                    核心人员
                {% else %}
                    一般职员
                {% endif %}
            </td>
            <td>{{ empl.group.name }}</td>
            <td>
                <a href="{% url 'mainSystem:empl_del' %}?eid={{ empl.id }}" onclick="return confirm('真的要删除吗？')">删除</a>
                <a href="{% url 'mainSystem:empl_edit' %}?eid={{ empl.id }}">修改</a>
            </td>
        </tr>
         {% endfor %}
    </table>
{#    {% include 'mainSystem/page.html' %} <!--从外部引入分页功能，里面有函数没有提示-->#}
    <nav aria-label="Page navigation" class="text-center">
    <ul class="pagination">
        <!--上一页-->
        {% if empls.has_previous %} <!--内联没有提示，这里是内置函数,前面还有页码-->
        <li>
            <a href="?pn={{ empls.previous_page_number }}&wd={{ request.GET.wd }}" aria-label="Previous"> <!--内联没有提示，这里是内置函数,pn=前一页页码-->
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}
        <!--end-->

        <!--分页数字-->
        {% for num in page_nums %}
            {% if num == empls.number %} <!--当前页-->
                <li class="active"><a href="?pn={{ num }}&wd={{ request.GET.wd }}">{{ num }}</a></li>
            {% else %} <!--非当前页-->
                <li><a href="?pn={{ num }}&wd={{ request.GET.wd }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if empls.has_next %}
        <li>
            <a href="?pn={{ empls.next_page_number }}&wd={{ request.GET.wd }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

StaffingSystem/templates/mainSystem/menu.html
 <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="{{ index }}"><a href="{% url 'mainSystem:index' %}">员工管理 <span class="sr-only">(current)</span></a></li>
            <li class="{{ manage }}"><a href="{% url 'mainSystem:empl_add' %}">增加员工</a></li>
            <li class="{{ advancedSearch }}"><a href="{% url 'mainSystem:advancedSearch' %}">高级查询</a></li>
            <li class="{{ config }}"><a href="{% url 'mainSystem:config' %}">系统配置</a></li>
            <li><a href="#">退出系统</a></li>
          </ul>
 </div>

StaffingSystem/templates/mainSystem/reg.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="{% static 'mainSystem/js/jquery.min.js' %}"></script>
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'mainSystem/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'mainSystem/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'mainSystem/css/signin.css' %}" rel="stylesheet">

  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post">
        <h2 class="form-signin-heading">注册</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
          <!--姓名检测 id指定为inputName-->
        <input type="text" name="username" id="inputName" class="form-control" placeholder="用户名" required="" autofocus="">
          <span class="namecheck"></span>   <!--姓名检测-->
          <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password1" id="inputPassword" class="form-control" placeholder="密码" required=""><label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password2" id="inputPassword" class="form-control" placeholder="确认密码" required=""><label for="inputPassword" class="sr-only">Password</label>
        <input type="text" name="nick" id="" class="form-control" placeholder="昵称" required="">
        <input type="text" name="telphone" id="" class="form-control" placeholder="电话" required="">
        <div>
            <span style="color: red">{{ error }}</span>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">提交</button>
      </form>

    </div> <!-- /container -->

    <script src="{% static 'mainSystem/js/ie10-viewport-bug-workaround.js' %}"></script>
    <script type="text/javascript">
        //dom加载完毕则执行回调函数
        //dom加载完毕则执行回掉函数
        $(document).ready(function(){
            $('#inputName').blur(function(){ //失去焦点事件
                var name = $(this).val() //获取文本框中的内容中
                $.get('{% url 'mainSystem:checkname' %}',{name:name},function(callback){ //用ajax 发起get请求
                    if (callback == 'ok'){  //用户名ok 可以注册
                        $('.namecheck').text('用户名可以注册').css('color','green')
                    }
                    else{
                        $('.namecheck').text(callback).css('color','red')
                    }
                }); // get 的 p1 : http请求地址  p2 get请求的查询参数是什么   p3 : 回调函数
            })
        })
    </script>

</body></html>